In [1]:
import numpy as np

In [3]:
# Crear arreglo de 1 dimension con 5 elementos
arr1 = np.array([1,2,3,4,5, 6])

print('Arreglo 1D', arr1)
print('Forma(shape): ', arr1.shape)
print('Tipos de datos (dtype)', arr1.dtype)

Arreglo 1D [1 2 3 4 5 6]
Forma(shape):  (6,)
Tipos de datos (dtype) int64


In [4]:
# Cambiar la forma del arreglo a una matriz 2 * 3
arr2 = arr1.reshape((2,3))
print('Arreglo 2D', arr2)
print('Forma(shape); ',arr2.shape)
print('Tipo de datos (dtype)', arr2.dtype)

Arreglo 2D [[1 2 3]
 [4 5 6]]
Forma(shape);  (2, 3)
Tipo de datos (dtype) int64


In [5]:
# Crear una matriz con forma (4,4) con numeros aleatorios entre 0 y 1
matrix = np.random.rand(4,4)
print('Arreglo 2D', matrix)
print('Forma(shape); ',matrix.shape)
print('Tipo de datos (dtype)', matrix.dtype)

Arreglo 2D [[0.74396843 0.43208394 0.0774242  0.99338013]
 [0.77467407 0.96155985 0.26040674 0.45108572]
 [0.12578425 0.51873086 0.81158993 0.07908021]
 [0.36760704 0.46059767 0.67438698 0.7538988 ]]
Forma(shape);  (4, 4)
Tipo de datos (dtype) float64


In [ ]:
# Crear un arreglo de 2 dimensiones a partir de una lista de listas
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Crear un arreglo de ceros con una forma (3,4)
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Crear un arreglo con unos con una forma (2,2)
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [9]:
# Crear una matriz identidad
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Crear un arreglo 3d de ceros con forma (2,3,4)
arr = np.zeros((2,3,4))
arr[0,1,2] = 5
arr

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
# Crear un arreglo 3D que se genere aleatoriamente con 2 filas y 5 columnas
arr = np.random.rand(2,5)
arr

array([[0.72419985, 0.40514866, 0.76082853, 0.80819598, 0.18193251],
       [0.36504198, 0.85328938, 0.0667576 , 0.59476763, 0.84028324]])

In [14]:
arr.T

array([[0.72419985, 0.36504198],
       [0.40514866, 0.85328938],
       [0.76082853, 0.0667576 ],
       [0.80819598, 0.59476763],
       [0.18193251, 0.84028324]])

In [15]:
 arr1 = np.array([[1,2], [3,4]])
 arr2 = np.array([[5,6], [7,8]])
 arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [16]:
# Concatenar arreglos horizontalmente
arr_h = np.hstack((arr1, arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [17]:
# Concatenar arreglos verticalmente
arr_v = np.stack((arr1, arr2))
arr_v

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])