In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# Calcular la suma de los elementos
suma = np.sum(arr)
suma

np.int64(15)

In [4]:
# Calcular el promedio de los elementos
promedio = np.mean(arr)
promedio

np.float64(3.0)

In [5]:
mediana = np.median(arr)
mediana

np.float64(3.0)

In [6]:
# Calcular el producto de los elementos
producto = np.prod(arr)
producto

np.int64(120)

In [7]:
# Desviacion estandar
desv_est = np.std(arr)
desv_est

np.float64(1.4142135623730951)

In [8]:
# Varianza
var = np.var(arr)
var

np.float64(2.0)

In [9]:
# minimo de los elementos
minimo = np.min(arr)
# maximo de los elementos
maximo = np.max(arr)
minimo, maximo

(np.int64(1), np.int64(5))

In [10]:
# Calcular la suma acumulativa
cumsum = np.cumsum(arr)
cumsum

array([ 1,  3,  6, 10, 15])

In [12]:
# Suma element-wise
arr + arr

array([ 2,  4,  6,  8, 10])

In [13]:
# Resta element-wise
arr - arr

array([0, 0, 0, 0, 0])

In [14]:
# Multiplicacion element-wise
arr * arr

array([ 1,  4,  9, 16, 25])

In [15]:
arr / arr

array([1., 1., 1., 1., 1.])