In [1]:
import numpy as np

In [3]:
# Crear arreglo de 1 dimension con 5 elementos
arr1 = np.array([1,2,3,4,5, 6])

print('Arreglo 1D', arr1)
print('Forma(shape): ', arr1.shape)
print('Tipos de datos (dtype)', arr1.dtype)

Arreglo 1D [1 2 3 4 5 6]
Forma(shape):  (6,)
Tipos de datos (dtype) int64


In [4]:
# Cambiar la forma del arreglo a una matriz 2 * 3
arr2 = arr1.reshape((2,3))
print('Arreglo 2D', arr2)
print('Forma(shape); ',arr2.shape)
print('Tipo de datos (dtype)', arr2.dtype)

Arreglo 2D [[1 2 3]
 [4 5 6]]
Forma(shape);  (2, 3)
Tipo de datos (dtype) int64


In [5]:
# Crear una matriz con forma (4,4) con numeros aleatorios entre 0 y 1
matrix = np.random.rand(4,4)
print('Arreglo 2D', matrix)
print('Forma(shape); ',matrix.shape)
print('Tipo de datos (dtype)', matrix.dtype)

Arreglo 2D [[0.74396843 0.43208394 0.0774242  0.99338013]
 [0.77467407 0.96155985 0.26040674 0.45108572]
 [0.12578425 0.51873086 0.81158993 0.07908021]
 [0.36760704 0.46059767 0.67438698 0.7538988 ]]
Forma(shape);  (4, 4)
Tipo de datos (dtype) float64
